version: '3.9'
services:
  db:
    image: postgres
    restart: always
    container_name: postgres-ax-technology
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: ax-technology
    volumes:
      - ax-technology_data:/var/lib/postgresql/data

  myapp:
    container_name: medium-lite
    build: .
    ports:
      - "3005:3000"
      - '5556:5555'
    environment:
      DATABASE_URL: postgresql://postgres:123321@postgres-ax-technology:5432/shop?schema=public
      REDIS_HOST: my-redis
      REDIS_PORT: 6379
    depends_on:
      - db


volumes:
  ax-technology_data:
